//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import <AVFoundation/AVFoundation.h>

//#import "AVCaptureMetadataOutputObjectsDelegate.h"
//#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureMetadataOutput, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, NSArray, NSMutableArray, NSString, UIView;

@interface LBXScanNative : NSObject //<AVCaptureMetadataOutputObjectsDelegate, AVCaptureVideoDataOutputSampleBufferDelegate>
{
    _Bool bNeedScanResult;
    _Bool bHadAutoVideoZoom;
    _Bool _autoVideoZoom;
    _Bool _autoTorch;
    _Bool _isNeedCaputureImage;
    AVCaptureDevice *_device;
    AVCaptureDeviceInput *_input;
    AVCaptureMetadataOutput *_output;
    AVCaptureVideoDataOutput *_lightOutPut;
    AVCaptureSession *_session;
    AVCaptureVideoPreviewLayer *_preview;
    AVCaptureStillImageOutput *_stillImageOutput;
    id/*CDUnknownBlockType*/ _torchDidChanged;
    NSMutableArray *_arrayResult;
    NSArray *_arrayBarCodeType;
    UIView *_videoPreView;
    id/*CDUnknownBlockType*/ _blockScanResult;
}

+ (id)addImage:(id)arg1 toImage:(id)arg2;
+ (id)createBarCodeWithString:(id)arg1 QRSize:(struct CGSize)arg2;
+ (id)createQRWithString:(id)arg1 QRSize:(struct CGSize)arg2 QRColor:(id)arg3 bkColor:(id)arg4;
+ (id)createAlipayQRWithString:(id)arg1 QRSize:(struct CGSize)arg2;
+ (id)createQRWithString:(id)arg1 QRSize:(struct CGSize)arg2;
+ (id)createQRForString:(id)arg1;
+ (id)createNonInterpolatedUIImageFormCIImage:(id)arg1 withSize:(double)arg2;
+ (void)recognizeImage:(id)arg1 success:(void(^)(NSArray *list))arg2;
@property(copy, nonatomic) id/*CDUnknownBlockType*/ blockScanResult; // @synthesize blockScanResult=_blockScanResult;
@property(nonatomic) __weak UIView *videoPreView; // @synthesize videoPreView=_videoPreView;
@property(retain, nonatomic) NSArray *arrayBarCodeType; // @synthesize arrayBarCodeType=_arrayBarCodeType;
@property(retain, nonatomic) NSMutableArray *arrayResult; // @synthesize arrayResult=_arrayResult;
@property(copy, nonatomic) id/*CDUnknownBlockType*/ torchDidChanged; // @synthesize torchDidChanged=_torchDidChanged;
@property(nonatomic) _Bool isNeedCaputureImage; // @synthesize isNeedCaputureImage=_isNeedCaputureImage;
@property(retain, nonatomic) AVCaptureStillImageOutput *stillImageOutput; // @synthesize stillImageOutput=_stillImageOutput;
@property(nonatomic, getter=isAutoTorch) _Bool autoTorch; // @synthesize autoTorch=_autoTorch;
@property(nonatomic, getter=isAutoVideoZoom) _Bool autoVideoZoom; // @synthesize autoVideoZoom=_autoVideoZoom;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *preview; // @synthesize preview=_preview;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVCaptureVideoDataOutput *lightOutPut; // @synthesize lightOutPut=_lightOutPut;
@property(retain, nonatomic) AVCaptureMetadataOutput *output; // @synthesize output=_output;
@property(retain, nonatomic) AVCaptureDeviceInput *input; // @synthesize input=_input;
@property(nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
- (void)changeVideoScale:(id)arg1;
- (id)defaultMetaDataObjectTypes;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)captureImage;
- (id)connectionWithMediaType:(id)arg1 fromConnections:(id)arg2;
- (id)getImageFromLayer:(id)arg1 size:(struct CGSize)arg2;
- (void)changeTorch;
- (void)setTorch:(_Bool)arg1;
- (void)stopScan;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)startScan;
- (void)changeScanType:(id)arg1;
- (void)setScanRect:(struct CGRect)arg1;
- (void)setVideoScale:(double)arg1;
- (double)getVideoMaxScale;
- (void)initParaWithPreView:(id)arg1 ObjectType:(id)arg2 cropRect:(struct CGRect)arg3 success:(id/*CDUnknownBlockType*/)arg4;
- (id)initWithPreView:(id)arg1 ObjectType:(id)arg2 success:(id/*CDUnknownBlockType*/)arg3;
- (id)initWithPreView:(id)arg1 ObjectType:(id)arg2 cropRect:(struct CGRect)arg3 success:(id/*CDUnknownBlockType*/)arg4;
- (void)setNeedCaptureImage:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

