//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NIMMessage, NIMMessageReceipt, NIMSession, NSArray, NIMTeamMessageReceiptDetail;
@protocol NIMChatManagerDelegate;

@protocol NIMChatManager <NSObject>
- (void)removeDelegate:(id <NIMChatManagerDelegate>)arg1;
- (void)addDelegate:(id <NIMChatManagerDelegate>)arg1;
- (float)messageTransportProgress:(NIMMessage *)arg1;
- (_Bool)messageInTransport:(NIMMessage *)arg1;
- (void)cancelFetchingMessageAttachment:(NIMMessage *)arg1;
- (_Bool)fetchMessageAttachment:(NIMMessage *)arg1 error:(id *)arg2;
- (void)revokeMessage:(NIMMessage *)arg1 completion:(void (^)(NSError *))arg2;
- (void)queryMessageReceiptDetail:(NIMMessage *)arg1 completion:(void (^)(NSError *, NIMTeamMessageReceiptDetail *))arg2;
- (void)refreshTeamMessageReceipts:(NSArray *)arg1;
- (void)sendTeamMessageReceipts:(NSArray *)arg1 completion:(void (^)(NSError *, NSArray *))arg2;
- (void)sendMessageReceipt:(NIMMessageReceipt *)arg1 completion:(void (^)(NSError *))arg2;
- (_Bool)forwardMessage:(NIMMessage *)arg1 toSession:(NIMSession *)arg2 error:(id *)arg3;
- (_Bool)resendMessage:(NIMMessage *)arg1 error:(id *)arg2;
- (_Bool)sendMessage:(NIMMessage *)arg1 toSession:(NIMSession *)arg2 error:(id *)arg3;
@end

