//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@protocol NIMCustomAttachment <NSObject>
- (NSString *)encodeAttachment;

@optional
- (NSString *)attachmentPathForDownloading;
- (NSString *)attachmentURLStringForDownloading;
- (_Bool)attachmentNeedsDownload;
- (void)updateAttachmentURL:(NSString *)arg1;
- (NSString *)attachmentPathForUploading;
- (_Bool)attachmentNeedsUpload;
@end

