//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NIMChatManager.h"

@class NSString;

@interface NIMChatManagerWrapper : NSObject <NIMChatManager>
{
}

+ (id)sharedWrapper;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (float)messageTransportProgress:(id)arg1;
- (_Bool)messageInTransport:(id)arg1;
- (void)cancelFetchingMessageAttachment:(id)arg1;
- (_Bool)fetchMessageAttachment:(id)arg1 error:(id *)arg2;
- (void)queryMessageReceiptDetail:(id)arg1 completion:(/*CDUnknownBlockType*/)arg2;
- (void)refreshTeamMessageReceipts:(id)arg1;
- (void)revokeMessage:(id)arg1 completion:(/*CDUnknownBlockType*/)arg2;
- (void)sendTeamMessageReceipts:(id)arg1 completion:(/*CDUnknownBlockType*/)arg2;
- (void)sendMessageReceipt:(id)arg1 completion:(/*CDUnknownBlockType*/)arg2;
- (_Bool)forwardMessage:(id)arg1 toSession:(id)arg2 error:(id *)arg3;
- (_Bool)resendMessage:(id)arg1 error:(id *)arg2;
- (_Bool)sendMessage:(id)arg1 toSession:(id)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

