//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NIMMessageObject-Protocol.h"
#import "NIMMessageObject_Private-Protocol.h"

@class NIMMessage, NSString;
@protocol NIMCustomAttachment;

@interface NIMCustomObject : NSObject <NIMMessageObject_Private, NIMMessageObject>
{
    NIMMessage *_message;
    id <NIMCustomAttachment> _attachment;
}

+ (void)registerCustomDecoder:(id)arg1;
@property(retain, nonatomic) id <NIMCustomAttachment> attachment; // @synthesize attachment=_attachment;
@property(nonatomic) __weak NIMMessage *message; // @synthesize message=_message;
- (id)fileParamForDownload;
- (id)prepareForDownLoad;
- (_Bool)needsDownloadAttachment;
- (void)setUploadURL:(id)arg1;
- (_Bool)needUpload;
- (id)filepathForUpload;
- (void)decodeWithContent:(id)arg1;
- (id)encodeContent;
- (long long)type;
@property(readonly, copy) NSString *description;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

