//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NIMMessage, NIMRevokeMessageNotification, NSArray, NSError, NSString;

@protocol NIMChatManagerDelegate <NSObject>

@optional
- (void)fetchMessageAttachment:(NIMMessage *)arg1 didCompleteWithError:(NSError *)arg2;
- (void)fetchMessageAttachment:(NIMMessage *)arg1 progress:(float)arg2;
- (void)onRecvRevokeMessageNotification:(NIMRevokeMessageNotification *)arg1;
- (void)onRecvMessageReceipts:(NSArray *)arg1;
- (void)onRecvMessages:(NSArray *)arg1;
- (void)sendMessage:(NIMMessage *)arg1 didCompleteWithError:(NSError *)arg2;
- (void)sendMessage:(NIMMessage *)arg1 progress:(float)arg2;
- (void)uploadAttachmentSuccess:(NSString *)arg1 forMessage:(NIMMessage *)arg2;
- (void)willSendMessage:(NIMMessage *)arg1;
@end

