//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NIMResourceManager-Protocol.h"

@class NIMDownloader, NIMNOSUploader, NSMutableDictionary, NSString;

@interface NIMFileCenter : NSObject <NIMResourceManager>
{
    NSMutableDictionary *_uploadFiles;
    NIMNOSUploader *_uploader;
    NSMutableDictionary *_downloadFiles;
    NIMDownloader *_downloader;
    long long _fileQuickTransferThreshold;
}

@property(nonatomic) long long fileQuickTransferThreshold; // @synthesize fileQuickTransferThreshold=_fileQuickTransferThreshold;
@property(retain, nonatomic) NIMDownloader *downloader; // @synthesize downloader=_downloader;
@property(retain, nonatomic) NSMutableDictionary *downloadFiles; // @synthesize downloadFiles=_downloadFiles;
@property(retain, nonatomic) NIMNOSUploader *uploader; // @synthesize uploader=_uploader;
@property(retain, nonatomic) NSMutableDictionary *uploadFiles; // @synthesize uploadFiles=_uploadFiles;
- (id)videoThumbnailURL:(id)arg1;
- (id)imageThumbnailURL:(id)arg1;
- (id)searchFilesInPath:(id)arg1 option:(id)arg2;
- (void)removeResourceFiles:(id)arg1 completion:(id/*CDUnknownBlockType*/)arg2;
- (void)searchResourceFiles:(id)arg1 completion:(id/*CDUnknownBlockType*/)arg2;
- (id)normalizeURLString:(id)arg1;
- (id)convertURLToAcceleratedURL:(id)arg1;
- (id)convertHttpToHttps:(id)arg1;
- (void)cancelTask:(id)arg1 inFiles:(id)arg2;
- (void)cancelTask:(id)arg1;
- (void)notifyDownloadResult:(id)arg1 error:(id)arg2 forFile:(id)arg3;
- (void)notifyDownloadProgress:(float)arg1 forFile:(id)arg2;
- (id)download:(id)arg1 filepath:(id)arg2;
- (void)download:(id)arg1 filepath:(id)arg2 progress:(id/*CDUnknownBlockType*/)arg3 completion:(id/*CDUnknownBlockType*/)arg4;
- (void)notifyUploadResult:(id)arg1 error:(id)arg2 forFile:(id)arg3;
- (void)notifyUploadProgress:(float)arg1 forFile:(id)arg2;
- (void)upload:(id)arg1 scene:(id)arg2 progress:(id/*CDUnknownBlockType*/)arg3 completion:(id/*CDUnknownBlockType*/)arg4;
- (void)upload:(id)arg1 progress:(id/*CDUnknownBlockType*/)arg2 completion:(id/*CDUnknownBlockType*/)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

