//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NIMMessageObject-Protocol.h"
#import "NIMMessageObject_Private-Protocol.h"

@class NIMImageOption, NIMMessage, NSData, NSString, UIImage;

@interface NIMImageObject : NSObject <NIMMessageObject_Private, NIMMessageObject>
{
    NIMMessage *_message;
    NSString *_displayName;
    NIMImageOption *_option;
    long long _fileLength;
    NSString *_md5;
    NSString *_fileName;
    NSString *_url;
    UIImage *_sourceImage;
    NSString *_sourceFilepath;
    NSData *_sourceData;
    NSString *_sourceExtension;
    NSString *_scene;
    struct CGSize _size;
}

@property(retain, nonatomic) NSString *scene; // @synthesize scene=_scene;
@property(copy, nonatomic) NSString *sourceExtension; // @synthesize sourceExtension=_sourceExtension;
@property(retain, nonatomic) NSData *sourceData; // @synthesize sourceData=_sourceData;
@property(copy, nonatomic) NSString *sourceFilepath; // @synthesize sourceFilepath=_sourceFilepath;
@property(retain, nonatomic) UIImage *sourceImage; // @synthesize sourceImage=_sourceImage;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(copy, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(nonatomic) long long fileLength; // @synthesize fileLength=_fileLength;
@property(retain, nonatomic) NIMImageOption *option; // @synthesize option=_option;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(nonatomic) __weak NIMMessage *message; // @synthesize message=_message;
- (_Bool)prepareByData;
- (_Bool)prepareByFilepath;
- (_Bool)prepareByImage;
- (id)prepareForSend;
@property(readonly, copy, nonatomic) NSString *thumbPath;
@property(readonly, copy, nonatomic) NSString *path;
@property(readonly, copy, nonatomic) NSString *thumbUrl;
- (id)thumbName;
- (id)imageName;
- (id)fileParamForDownload;
- (id)prepareForDownLoad;
- (void)setMessageScene:(id)arg1;
- (id)messageScene;
- (id)uploadURL;
- (void)setUploadURL:(id)arg1;
- (_Bool)needUpload;
- (id)filepathForUpload;
- (void)decodeWithContent:(id)arg1;
- (id)encodeContent;
@property(readonly, copy) NSString *description;
- (long long)type;
- (id)init;
- (id)initWithData:(id)arg1 extension:(id)arg2 scene:(id)arg3;
- (id)initWithFilepath:(id)arg1 scene:(id)arg2;
- (id)initWithImage:(id)arg1 scene:(id)arg2;
- (id)initWithData:(id)arg1 extension:(id)arg2;
- (id)initWithFilepath:(id)arg1;
- (id)initWithImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

