//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NIMMessage;

@interface NIMMessageInfo : NSObject
{
    float _progress;
    NIMMessage *_message;
}

@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(retain, nonatomic) NIMMessage *message; // @synthesize message=_message;

@end

