//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SMViewController.h"

//#import "NIMChatManagerDelegate.h"
//#import "NIMConversationManagerDelegate.h"
//#import "NIMInputActionDelegate.h"
//#import "NIMInputDelegate.h"
//#import "NIMMediaManagerDelegate.h"
//#import "NIMMessageCellDelegate.h"
//#import "NIMSessionInteractorDelegate.h"
//#import "PopActionSheetDelegate.h"
//#import "SMInputAudioButtonDelegate.h"
//#import "SMMessageMutilSelectViewDelegate.h"
//#import "SMMicrophoneViewDelegate.h"
//#import "UIScrollViewDelegate.h"

@class NIMInputView, NIMMessage, NIMSession, NIMSessionConfigurator, NSIndexPath, NSString, SMBaseTableView, SMMessageMutilSelectView, SMNewMessageButton, SMPopView, UIButton, UIImageView, UILabel;
@protocol NIMSessionInteractor;

@interface NIMSessionViewController : SMViewController //<UIScrollViewDelegate, NIMMediaManagerDelegate, NIMInputDelegate, SMMicrophoneViewDelegate, PopActionSheetDelegate, SMMessageMutilSelectViewDelegate, SMInputAudioButtonDelegate, NIMSessionInteractorDelegate, NIMInputActionDelegate, NIMMessageCellDelegate, NIMChatManagerDelegate, NIMConversationManagerDelegate>
{
    _Bool _noResignInputView;
    _Bool _shouldShowNewMessageTip;
    _Bool _isMuiltSelecting;
    _Bool _isOpen;
    SMBaseTableView *_tableView;
    NIMInputView *_sessionInputView;
    SMMessageMutilSelectView *_sessionMsgMutilSelectView;
    NIMSession *_session;
    id <NIMSessionInteractor> _interactor;
    NIMMessage *_firstMsg;
    long long _unreadCount;
    SMNewMessageButton *_scrollToBottomBtn;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    NSString *_cellphone;
    NIMMessage *_messageForMenu;
    UIButton *_upBtn;
    UIImageView *_closeImg;
    NSIndexPath *_lastVisibleIndexPathBeforeRotation;
    NIMSessionConfigurator *_configurator;
    SMPopView *_sendTextPopView;
}

@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(retain, nonatomic) SMPopView *sendTextPopView; // @synthesize sendTextPopView=_sendTextPopView;
@property(retain, nonatomic) NIMSessionConfigurator *configurator; // @synthesize configurator=_configurator;
@property(retain, nonatomic) NSIndexPath *lastVisibleIndexPathBeforeRotation; // @synthesize lastVisibleIndexPathBeforeRotation=_lastVisibleIndexPathBeforeRotation;
@property(retain, nonatomic) UIImageView *closeImg; // @synthesize closeImg=_closeImg;
@property(retain, nonatomic) UIButton *upBtn; // @synthesize upBtn=_upBtn;
@property(retain, nonatomic) NIMMessage *messageForMenu; // @synthesize messageForMenu=_messageForMenu;
@property(retain, nonatomic) NSString *cellphone; // @synthesize cellphone=_cellphone;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) _Bool isMuiltSelecting; // @synthesize isMuiltSelecting=_isMuiltSelecting;
@property(retain, nonatomic) SMNewMessageButton *scrollToBottomBtn; // @synthesize scrollToBottomBtn=_scrollToBottomBtn;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(nonatomic) _Bool shouldShowNewMessageTip; // @synthesize shouldShowNewMessageTip=_shouldShowNewMessageTip;
@property(retain, nonatomic) NIMMessage *firstMsg; // @synthesize firstMsg=_firstMsg;
@property(nonatomic) __weak id <NIMSessionInteractor> interactor; // @synthesize interactor=_interactor;
@property(nonatomic) _Bool noResignInputView; // @synthesize noResignInputView=_noResignInputView;
@property(retain, nonatomic) NIMSession *session; // @synthesize session=_session;
@property(retain, nonatomic) SMMessageMutilSelectView *sessionMsgMutilSelectView; // @synthesize sessionMsgMutilSelectView=_sessionMsgMutilSelectView;
@property(retain, nonatomic) NIMInputView *sessionInputView; // @synthesize sessionInputView=_sessionInputView;
@property(retain, nonatomic) SMBaseTableView *tableView; // @synthesize tableView=_tableView;
- (void)updateMessageUi:(id)arg1;
- (void)scrollToBottomClicked;
- (void)current:(id)arg1 SelectIndex:(long long)arg2 andMenuType:(long long)arg3;
- (void)titleButtonClicked:(id)arg1;
- (void)onSendQuoteMessage:(id)arg1 text:(id)arg2 atUsers:(id)arg3;
- (void)refreshSessionSubTitle:(id)arg1;
- (void)refreshSessionTitle:(id)arg1;
- (void)setUpTitleView;
- (id)conversationManager;
- (_Bool)shouldHandleReceipt;
- (void)removeListener;
- (void)addListener;
- (void)sendMessageReceipt:(id)arg1;
- (void)markRead;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)onTapMediaItemContactor:(id)arg1;
- (void)onTapMediaItemLocation:(id)arg1;
- (void)onTapMediaItemShoot:(id)arg1;
- (void)onTapMediaItemPicture:(id)arg1;
- (void)uiCheckReceipt;
- (void)uiShowMessage:(id)arg1;
- (void)uiUpdateMessage:(id)arg1;
- (id)uiDeleteMessage:(id)arg1;
- (void)uiInsertMessages:(id)arg1;
- (void)uiAddMessages:(id)arg1;
- (void)menuDidHide:(id)arg1;
- (void)deleteMsg:(id)arg1;
- (void)copyText:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)menusItems:(id)arg1;
- (long long)recordAudioType;
- (_Bool)shouldShowInputView;
- (_Bool)shouldAutoMarkRead;
- (_Bool)shouldAddListenerForNewMsg;
- (id)sessionConfig;
- (void)mutilyForwardMessage:(id)arg1 style:(long long)arg2;
- (void)chooseForwardStyle:(id)arg1;
- (void)mutilSelectView:(id)arg1 forwardBtnDidClick:(id)arg2;
- (void)onDeleteMessage:(id)arg1 deleteType:(int)arg2;
- (void)mutilSelectView:(id)arg1 deleteBtnDidClick:(id)arg2;
- (void)audioPlayDidBegan:(id)arg1 model:(id)arg2;
- (_Bool)disableAudioPlayedStatusIcon:(id)arg1;
- (_Bool)removeUITextEffectsWindow;
- (_Bool)canBecomeFirstResponder;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)willHideEditMenu:(id)arg1;
- (_Bool)onLongPressCell:(id)arg1 inView:(id)arg2;
- (void)onRetryMessage:(id)arg1;
- (_Bool)onTapCell:(id)arg1;
- (void)onStartRecording;
- (void)onStopRecording;
- (void)onCancelRecording;
- (id)robotsToSend:(id)arg1;
- (void)startWithRecordType:(id)arg1;
- (void)recordVideoFileFullPath:(id)arg1 translateText:(id)arg2;
- (void)recordAudioFileFullPath:(id)arg1 translateText:(id)arg2;
- (void)onSendText:(id)arg1 atUsers:(id)arg2;
- (void)onTextChanged:(id)arg1;
- (_Bool)onTapMediaItem:(id)arg1;
- (void)onLongPressSendText:(id)arg1;
- (void)didShowKeyboard;
- (void)didResignKeyboard;
- (void)didChangeInputHeight:(double)arg1;
- (void)showRecordFileNotSendReason;
- (_Bool)recordFileCanBeSend:(id)arg1;
- (void)onRecordFailed:(id)arg1;
- (void)recordAudioInterruptionBegin;
- (void)recordAudioProgress:(double)arg1;
- (void)recordAudioDidCancelled;
- (void)recordAudio:(id)arg1 didCompletedWithError:(id)arg2;
- (void)recordAudio:(id)arg1 didBeganWithError:(id)arg2;
- (void)messagesDeletedInSession:(id)arg1;
- (void)onRecvMessageReceipt:(id)arg1;
- (void)fetchMessageAttachment:(id)arg1 didCompleteWithError:(id)arg2;
- (void)fetchMessageAttachment:(id)arg1 progress:(float)arg2;
- (void)updateMessageYYCache:(id)arg1;
- (void)onRecvRevokeMessageNotification:(id)arg1;
- (void)onRecvMessages:(id)arg1;
- (void)sendMessage:(id)arg1 progress:(float)arg2;
- (void)sendMessage:(id)arg1 didCompleteWithError:(id)arg2;
- (void)willSendMessage:(id)arg1;
- (id)sessionSubTitle;
- (id)sessionTitle;
- (void)didRefreshMessageData;
- (id)createNewMessageIndicator:(id)arg1;
- (void)didFetchMessageData;
- (void)sendContactCardMessage;
- (void)onSendMessagePointForType:(long long)arg1 success:(_Bool)arg2;
- (void)onSendMessagePointForImageOrVideo:(_Bool)arg1 success:(_Bool)arg2;
- (void)sendMessage:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupScrollToBottomBtn;
- (void)setupConfigurator;
- (void)setUpMsgMutilSelevtView;
- (void)setupInputView;
- (void)reloadDataTableView:(_Bool)arg1;
- (void)setupTableView;
- (void)setClose;
- (void)setUpCloseBtn;
- (void)setupNav;
- (void)hiddenAt:(id)arg1;
- (void)showAt:(id)arg1;
- (void)willHideEditMenuNew:(id)arg1;
- (void)addObservers;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithSession:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)endObserver;
- (void)startObserver;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

