//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSMutableDictionary;

@interface NIMSessionManager : NSObject
{
    NSMutableDictionary *_messages;
}

@property(retain, nonatomic) NSMutableDictionary *messages; // @synthesize messages=_messages;
- (void)uploadAttachment:(id)arg1;
- (void)sendChatroomMessage:(id)arg1;
- (void)sendAppMessage:(id)arg1;
- (void)sendMessageByApp:(id)arg1;
- (void)fetchMessageAttachment:(id)arg1 didCompleteWithError:(void(^)(NSError *error))arg2;
- (void)fetchMessageAttachment:(id)arg1 progress:(float)arg2;
- (void)fireUploadSuccess:(id)arg1 forMessage:(id)arg2;
- (void)fireUploadError:(id)arg1 forMessage:(id)arg2;
- (void)sendMessage:(id)arg1 progress:(float)arg2;
- (void)removeMessage:(id)arg1;
- (_Bool)storeMessage:(id)arg1;
- (void)onRoomMsgAck:(id)arg1 messageId:(id)arg2 info:(id)arg3;
- (void)onMsgAck:(id)arg1 info:(id)arg2;
- (float)messageTransportProgress:(id)arg1;
- (_Bool)messageInTransport:(id)arg1;
- (void)cancelFetchingMessageAttachments:(id)arg1;
- (void)fetchMessageAttachments:(id)arg1;
- (void)sendMessage:(id)arg1;
- (id)init;

@end

