//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@interface NIMSession : NSObject <NSCopying>
{
    NSString *_sessionId;
    long long _sessionType;
}

+ (id)session:(id)arg1 type:(long long)arg2;
@property(nonatomic) long long sessionType; ///< 0：个人，1：群
@property(copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
- (id)remoteSessionKey;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

