//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NIMBackgroundTaskRunner, NIMLogCleaner, NIMSDKOption, NIMServerSetting, NSMutableDictionary, NSString;

@protocol NIMAntispamManager,NIMBroadcastManager,NIMRedPacketManager,NIMRobotManager,NIMEventSubscribeManager,NIMDocTranscodingManager,NIMChatroomManager,NIMResourceManager,NIMApnsManager,NIMSystemNotificationManager,NIMTeamManager,NIMUserManager,NIMMediaManager,NIMConversationManager,NIMChatManager,NIMLoginManager;

@interface NIMSDK : NSObject
{
    NIMServerSetting *_serverSetting;
    NSMutableDictionary *_sceneDict;
    NIMBackgroundTaskRunner *_runner;
    NIMLogCleaner *_cleaner;
    NSString *_localSessionId;
    NIMSDKOption *_option;
}

+ (id)sharedSDK;
@property(retain, nonatomic) NIMSDKOption *option; // @synthesize option=_option;
@property(copy, nonatomic) NSString *localSessionId; // @synthesize localSessionId=_localSessionId;
@property(retain, nonatomic) NIMLogCleaner *cleaner; // @synthesize cleaner=_cleaner;
@property(retain, nonatomic) NIMBackgroundTaskRunner *runner; // @synthesize runner=_runner;
@property(retain, nonatomic) NSMutableDictionary *sceneDict; // @synthesize sceneDict=_sceneDict;
@property(retain, nonatomic) NIMServerSetting *serverSetting; // @synthesize serverSetting=_serverSetting;
- (void)registerBadgeCountHandler:(id/*CDUnknownBlockType*/)arg1;
- (id)appTokenManager;
- (id)lbsManager;
- (id)pkToken;
- (id)apnsToken;
@property(readonly, nonatomic) id <NIMAntispamManager> antispamManager;
@property(readonly, nonatomic) id <NIMBroadcastManager> broadcastManager;
@property(readonly, nonatomic) id <NIMRedPacketManager> redPacketManager;
@property(readonly, nonatomic) id <NIMRobotManager> robotManager;
@property(readonly, nonatomic) id <NIMEventSubscribeManager> subscribeManager;
@property(readonly, nonatomic) id <NIMDocTranscodingManager> docTranscodingManager;
@property(readonly, nonatomic) id <NIMChatroomManager> chatroomManager;
@property(readonly, nonatomic) id <NIMResourceManager> resourceManager;
@property(readonly, nonatomic) id <NIMApnsManager> apnsManager;
@property(readonly, nonatomic) id <NIMSystemNotificationManager> systemNotificationManager;
@property(readonly, nonatomic) id <NIMTeamManager> teamManager;
@property(readonly, nonatomic) id <NIMUserManager> userManager;
@property(readonly, nonatomic) id <NIMMediaManager> mediaManager;
@property(readonly, nonatomic) id <NIMConversationManager> conversationManager;
@property(readonly, nonatomic) id <NIMChatManager> chatManager;
@property(readonly, nonatomic) id <NIMLoginManager> loginManager;
- (void)enableConsoleLog;
- (void)archiveLogs:(id/*CDUnknownBlockType*/)arg1;
- (id)currentLogFilepath;
- (void)updatePushKitToken:(id)arg1;
- (void)updateApnsToken:(id)arg1;
- (_Bool)isUsingDemoAppKey;
- (id)appKey;
- (void)registerWithOption:(id)arg1;
- (void)registerWithAppID:(id)arg1 cerName:(id)arg2;
- (id)sdkVersion;
- (id)init;

@end

