//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@interface NIMTeamMember : NSObject
{
    _Bool _isMuted;
    NSString *_teamId;
    NSString *_userId;
    NSString *_invitor;
    long long _type;
    NSString *_nickname;
    double _createTime;
    NSString *_customInfo;
}

@property(copy, nonatomic) NSString *customInfo; // @synthesize customInfo=_customInfo;
@property(readonly, nonatomic) double createTime; // @synthesize createTime=_createTime;
@property(readonly, nonatomic) _Bool isMuted; // @synthesize isMuted=_isMuted;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *invitor; // @synthesize invitor=_invitor;
@property(readonly, copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(readonly, copy, nonatomic) NSString *teamId; // @synthesize teamId=_teamId;
- (id)description;
- (id)initWithProperty:(const struct Property *)arg1;

@end

