//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NIMTeam;

@protocol NIMTeamManagerDelegate <NSObject>

@optional
- (void)onTeamMemberChanged:(NIMTeam *)arg1;
- (void)onTeamRemoved:(NIMTeam *)arg1;
- (void)onTeamUpdated:(NIMTeam *)arg1;
- (void)onTeamAdded:(NIMTeam *)arg1;
@end

