//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NIMSessionViewController.h"

//#import "M80AttributedLabelDelegate.h"
//#import "MFMailComposeViewControllerDelegate.h"
//#import "MFMessageComposeViewControllerDelegate.h"
//#import "MWPhotoBrowserDelegate.h"
//#import "NIMContactSelectDelegate.h"
//#import "NIMEventSubscribeManagerDelegate.h"
//#import "NIMMediaManagerDelegate.h"
//#import "NIMMessageCellDelegate.h"
//#import "NIMSystemNotificationManagerDelegate.h"
//#import "NIMTeamManagerDelegate.h"
//#import "NIMUserManagerDelegate.h"
//#import "NTESTimerHolderDelegate.h"
//#import "SFSafariViewControllerDelegate.h"
//#import "SMTRCircleContainViewDelegate.h"
//#import "SMTreasureManagerShowAlertDelegate.h"
//#import "UIDocumentInteractionControllerDelegate.h"
//#import "UIDocumentPickerDelegate.h"
//#import "UIImagePickerControllerDelegate.h"

@class ALAssetsLibrary, HFImageEditorViewController, NSMutableArray, NSMutableString, NSString, NTESCustomSysNotificationSender, NTESSessionConfig, NTESTimerHolder, SMAnnouncementPopView, SMBannerView, SMBaseAlertView, SMFriendLevelPopView, SMTRCircleContainView, UIImagePickerController, UIView;

@interface NTESSessionViewController : NIMSessionViewController //<MFMessageComposeViewControllerDelegate, SMTRCircleContainViewDelegate, SMTreasureManagerShowAlertDelegate, UIImagePickerControllerDelegate, NIMSystemNotificationManagerDelegate, NIMMediaManagerDelegate, NTESTimerHolderDelegate, NIMContactSelectDelegate, NIMEventSubscribeManagerDelegate, UIDocumentPickerDelegate, UIDocumentInteractionControllerDelegate, MWPhotoBrowserDelegate, SFSafariViewControllerDelegate, M80AttributedLabelDelegate, MFMailComposeViewControllerDelegate, NIMUserManagerDelegate, NIMTeamManagerDelegate, NIMMessageCellDelegate>
{
    NSMutableString *speachContent;
    SMBaseAlertView *_authorityAlert;
    _Bool _disableCommandTyping;
    _Bool _disableOnlineState;
    _Bool _needRecoverLastContrller;
    _Bool _shouldShowBanner;
    NTESCustomSysNotificationSender *_notificaionSender;
    NTESSessionConfig *_sessionConfig;
    UIImagePickerController *_imagePicker;
    NTESTimerHolder *_titleTimer;
    UIView *_currentSingleSnapView;
    SMBannerView *_bannerView;
    NSMutableArray *_photos;
    NSMutableArray *_thumbs;
    HFImageEditorViewController *_imageEditor;
    ALAssetsLibrary *_library;
    id <UINavigationControllerDelegate> _firstDelegate;
    SMAnnouncementPopView *_popView;
    SMFriendLevelPopView *_friendLevelPopView;
}

@property(retain, nonatomic) SMFriendLevelPopView *friendLevelPopView; // @synthesize friendLevelPopView=_friendLevelPopView;
@property(retain, nonatomic) SMAnnouncementPopView *popView; // @synthesize popView=_popView;
@property(nonatomic) __weak id <UINavigationControllerDelegate> firstDelegate; // @synthesize firstDelegate=_firstDelegate;
@property(retain, nonatomic) ALAssetsLibrary *library; // @synthesize library=_library;
@property(retain, nonatomic) HFImageEditorViewController *imageEditor; // @synthesize imageEditor=_imageEditor;
@property(retain, nonatomic) NSMutableArray *thumbs; // @synthesize thumbs=_thumbs;
@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
@property(nonatomic) _Bool shouldShowBanner; // @synthesize shouldShowBanner=_shouldShowBanner;
@property(retain, nonatomic) SMBannerView *bannerView; // @synthesize bannerView=_bannerView;
@property(retain, nonatomic) UIView *currentSingleSnapView; // @synthesize currentSingleSnapView=_currentSingleSnapView;
@property(retain, nonatomic) NTESTimerHolder *titleTimer; // @synthesize titleTimer=_titleTimer;
@property(retain, nonatomic) UIImagePickerController *imagePicker; // @synthesize imagePicker=_imagePicker;
@property(retain, nonatomic) NTESSessionConfig *sessionConfig; // @synthesize sessionConfig=_sessionConfig;
@property(retain, nonatomic) NTESCustomSysNotificationSender *notificaionSender; // @synthesize notificaionSender=_notificaionSender;
@property(nonatomic) _Bool needRecoverLastContrller; // @synthesize needRecoverLastContrller=_needRecoverLastContrller;
@property(nonatomic) _Bool disableOnlineState; // @synthesize disableOnlineState=_disableOnlineState;
@property(nonatomic) _Bool disableCommandTyping; // @synthesize disableCommandTyping=_disableCommandTyping;
- (void)onSendAction;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (id)documentInteractionControllerViewForPreview:(id)arg1;
- (id)documentInteractionControllerViewControllerForPreview:(id)arg1;
- (_Bool)shouldAutorotate;
- (void)setupNavIconButton;
- (void)setUpRightNarItem;
- (void)setUpNav;
- (id)cellActions;
- (_Bool)checkRTSCondition;
- (void)sendImageMessagePath:(id)arg1;
- (void)revokeAndReEditMessage:(id)arg1;
- (id)uiDeleteMessage:(id)arg1;
- (void)revokeMessage:(id)arg1;
- (void)cancelMutilSelect;
- (void)multiSelectAction:(id)arg1;
- (void)forwardMessage:(id)arg1;
- (void)quoteMessage:(id)arg1;
- (void)audio2Text:(id)arg1;
- (id)menusItems:(id)arg1;
- (void)jumpToSessionSetting;
- (void)showGroupManagerSettingVC;
- (void)showManagerAlert;
- (void)showCustom:(id)arg1;
- (void)showFile:(id)arg1;
- (void)showLocation:(id)arg1;
- (void)showVideo:(id)arg1;
- (void)photoBrowserDidFinishModalPresentation:(id)arg1;
- (void)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2 selectedChanged:(_Bool)arg3;
- (_Bool)photoBrowser:(id)arg1 isPhotoSelectedAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 didDisplayPhotoAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 save:(id)arg2 succeed:(_Bool)arg3;
- (id)photoBrowser:(id)arg1 thumbPhotoAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPhotosInPhotoBrowser:(id)arg1;
- (void)collectPhotoMessageAtIndex:(unsigned long long)arg1;
- (void)recogniseQRCodeImageAtIndex:(unsigned long long)arg1 Image:(id)arg2 photoBrowser:(id)arg3;
- (void)forwardPhotoMessageAtIndex:(unsigned long long)arg1;
- (void)photoBrowserOnMore:(id)arg1;
- (void)photoBrowserSingleTap:(id)arg1;
- (void)showImage:(id)arg1;
- (void)showPhotoBrowser:(id)arg1 at:(id)arg2;
- (id)messageSendSource:(id)arg1;
- (_Bool)onLongPressAvatar:(id)arg1;
- (_Bool)onTapAvatar:(id)arg1;
- (void)onDeleteMessage:(id)arg1 deleteType:(int)arg2;
- (id)convertAttach:(id)arg1;
- (_Bool)onTapCell:(id)arg1;
- (void)showRecordFileNotSendReason;
- (_Bool)recordFileCanBeSend:(id)arg1;
- (void)onRecordFailed:(id)arg1;
- (void)showAlertView;
- (void)showAlertView:(id)arg1;
- (void)judgeDealUserStatus;
- (void)sendMessage:(id)arg1 didCompleteWithError:(id)arg2;
- (void)statusBarFrameDidChange;
- (void)updateAudioWave:(id)arg1;
- (_Bool)teamLockState;
- (void)lockTeamIfNecessary;
- (void)favoriteLater:(id)arg1;
- (void)updateMsgToServer:(id)arg1;
- (void)report:(id)arg1;
- (void)remindMeLater:(id)arg1;
- (void)addToEmotion:(id)arg1;
- (void)collection:(id)arg1;
- (void)m80AttributedLabel:(id)arg1 clickedOnLink:(id)arg2;
- (void)hideBannerView;
- (void)showBannerView;
- (id)getAudioPath;
- (void)onTapMediaItemRedPacket:(id)arg1;
- (void)onTapMediaItemWhiteBoard:(id)arg1;
- (void)sendSnapchatMessage:(id)arg1;
- (void)sendSnapchatMessagePath:(id)arg1;
- (void)onSendFailed:(id)arg1;
- (void)onTapMediaItemFileTrans:(id)arg1;
- (void)onTapMediaItemTeamMeeting:(id)arg1;
- (void)onTapAnnounceItem:(id)arg1;
- (void)showVideoChat:(id)arg1;
- (void)onTapMediaItemSendVideo:(id)arg1;
- (void)onTapMediaItemVideoChat:(id)arg1;
- (void)onTapMediaItemAudioChat:(id)arg1;
- (void)onTapMediaItemJanKenPon:(id)arg1;
- (void)onTeamUpdated:(id)arg1;
- (void)onUserInfoChanged:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)onPressAdd;
- (void)onSelectChartlet:(id)arg1 catalog:(id)arg2;
- (void)onTextChanged:(id)arg1;
- (id)sessionSubTitle;
- (id)sessionTitle;
- (void)onNTESTimerFired:(id)arg1;
- (void)onReceiveCustomSystemNotification:(id)arg1;
- (void)onRecvMessages:(id)arg1;
- (void)didFetchMessageData;
- (void)onRecvSubscribeEvents:(id)arg1;
- (void)tableView:(id)arg1 didScrollToTopCellAt:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)announcementCheck;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)pop:(id)arg1;
- (void)viewDidLoad;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(long long)arg2;
- (id)parseCustomMessage:(id)arg1;
- (id)parseBodyViaMessage:(id)arg1;
- (void)sendSMS:(id)arg1 toUser:(id)arg2;
- (void)sendInviteMessagetoUsr:(id)arg1;
@property(retain, nonatomic) SMTRCircleContainView *treasureView;
- (void)jumpToChatIncomePage;
- (void)showChangeFriendAlert:(id)arg1;
- (void)addTipAlertView;
- (void)updateTreasureTalkProgress;
- (void)removeCornDelegate;
- (void)setUpdata;
- (void)setUpTreasureNavi;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

