//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LoginData.h"

@class LoginData, NSString;

@interface NTESLoginManager : NSObject
{
    LoginData *_currentLoginData;
    NSString *_filepath;
}

+ (id)getCurrentUser;
+ (id)sharedManager;
@property(copy, nonatomic) NSString *filepath; // @synthesize filepath=_filepath;
@property(retain, nonatomic) LoginData *currentLoginData; // @synthesize currentLoginData=_currentLoginData;
- (void)clearData;
- (void)saveData;
- (void)readData;
- (id)initWithPath:(id)arg1;

@end

