//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "GPBMessage.h"

@class NSString;

@interface OpenRequest : NSObject//GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *fromAccid; // @dynamic fromAccid;
@property(copy, nonatomic) NSString *originMessageId; // @dynamic originMessageId;
@property(copy, nonatomic) NSString *redPacketId; // @dynamic redPacketId;
@property(nonatomic) int redPacketType; // @dynamic redPacketType;
@property(copy, nonatomic) NSString *sessionId; // @dynamic sessionId;
@property(nonatomic) int sessionType; // @dynamic sessionType;

@end

