//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class GRPCProtoService;

@interface SMBaseApiManager : NSObject
{
    GRPCProtoService *_grpcService;
}

@property(readonly, nonatomic) GRPCProtoService *grpcService; // @synthesize grpcService=_grpcService;
- (void)handleApiError:(id)arg1;
- (id)errorWithApiError:(id)arg1;
- (void)handleCallback:(id/*CDUnknownBlockType*/)arg1 withGrpcResponse:(id)arg2 error:(id)arg3;
- (void)buildCommonHeaderForCall:(id)arg1;
- (id)basicParams;
- (id)host;
- (id)init;

@end

