//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SMBaseApiManager.h"

@class C2CRedPacketV2, SMHttpResponse;

@interface SMC2CRedPacketV2ApiManager : SMBaseApiManager
{
//    C2CRedPacketV2 *_grpcService;
}

@property(readonly, nonatomic) C2CRedPacketV2 *grpcService; // @synthesize grpcService=_grpcService;
- (void)asyncCheckUserWhetherInC2GWhiteListWithRequest:(id)arg1 callback:(void(^)(BOOL success,SMHttpResponse *resp))arg2;
- (void)asyncFetchRedPacketRecordListV2WithRequest:(id)arg1 callback:(void(^)(BOOL success,SMHttpResponse *resp))arg2;
- (void)asyncOpenRedPacketWithRequest:(id)arg1 callback:(void(^)(BOOL success,SMHttpResponse *resp))arg2;
- (void)asyncFetchReceivedListWithRequest:(id)arg1 callback:(void(^)(BOOL success,SMHttpResponse *resp))arg2;
- (void)asyncFetchRedPacketInfoWithRequest:(id)arg1 callback:(void(^)(BOOL success,SMHttpResponse *resp))arg2;
- (void)asyncFetchRedPacketStatusWithRequest:(id)arg1 callback:(void(^)(BOOL success,SMHttpResponse *resp))arg2;
- (void)asyncCreateOrderWithRequest:(id)arg1 callback:(void(^)(BOOL success,SMHttpResponse *resp))arg2;
- (id)host;
- (id)init;

@end

