//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSError, NSString;

@interface SMHttpResponse : NSObject
{
    NSError *_error;
    id _data;
    NSString *_msg;
}

@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(retain, nonatomic) id data; // @synthesize data=_data;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;

@end

