//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@protocol SMRedPacketDelegate <NSObject>
- (void)updateB2CRedPacketStatus:(unsigned long long)arg1;
- (void)redPacketSend:(_Bool)arg1;
- (void)updateGroupRedPacketStatus:(unsigned long long)arg1 isCollected:(_Bool)arg2;
- (void)updateRedPacketStatus:(unsigned long long)arg1;
@end

