//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface SMScanResultHandler : NSObject
{
    id/*CDUnknownBlockType*/ _imageCallback;
}

+ (id)sharedInstance;
@property(copy, nonatomic) id/*CDUnknownBlockType*/ imageCallback; // @synthesize imageCallback=_imageCallback;
- (void)showJoinGroupAlertWithTeamId:(id)arg1;
- (void)checkKickedStatusWithTid:(id)arg1;
- (void)applyToTeamWithTeamId:(id)arg1 message:(id)arg2;
- (void)fetchTeamInfoWithTeamId:(id)arg1;
- (void)recognizeImage:(id)arg1 callback:(id/*CDUnknownBlockType*/)arg2;
- (void)dealResultString:(id)arg1 callback:(id/*CDUnknownBlockType*/)arg2;
- (id)transformQRResult:(id)arg1;
- (id)getQRCode:(long long)arg1 with:(id)arg2;
- (id)getQRCodeURLWithType:(long long)arg1;

@end

