//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@interface SMUserProfile : NSObject <NSCoding>
{
    _Bool _hasLmIdSet;
    _Bool _hasPasswordSet;
    _Bool _hasFirstOnce;
    _Bool _hasSyncData;
    _Bool _hasFirstOnceForShowAddFriendAlert;
    _Bool _isFinishedInitContactsData;
    NSString *_id_p;
    NSString *_lmId;
    NSString *_nickname;
    NSString *_accid;
    NSString *_region;
    unsigned long long _userGender;
    NSString *_avatarURL;
    NSString *_phone;
    NSString *_signature;
    NSString *_alipayName;
    NSString *_weixinName;
    NSString *_qqName;
    NSString *_weiboName;
    unsigned long long _autoAddFriend;
}

+ (void)resetUserProfile:(id)arg1;
+ (unsigned long long)SMGenderFromRPCGender:(int)arg1;
+ (int)RPCGenderFromSMGender:(unsigned long long)arg1;
@property(nonatomic) unsigned long long autoAddFriend; // @synthesize autoAddFriend=_autoAddFriend;
@property(copy, nonatomic) NSString *weiboName; // @synthesize weiboName=_weiboName;
@property(copy, nonatomic) NSString *qqName; // @synthesize qqName=_qqName;
@property(copy, nonatomic) NSString *weixinName; // @synthesize weixinName=_weixinName;
@property(copy, nonatomic) NSString *alipayName; // @synthesize alipayName=_alipayName;
@property(copy, nonatomic) NSString *signature; // @synthesize signature=_signature;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(copy, nonatomic) NSString *avatarURL; // @synthesize avatarURL=_avatarURL;
@property(nonatomic) unsigned long long userGender; // @synthesize userGender=_userGender;
@property(copy, nonatomic) NSString *region; // @synthesize region=_region;
@property(retain, nonatomic) NSString *accid; // @synthesize accid=_accid;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(nonatomic) _Bool isFinishedInitContactsData; // @synthesize isFinishedInitContactsData=_isFinishedInitContactsData;
@property(nonatomic) _Bool hasFirstOnceForShowAddFriendAlert; // @synthesize hasFirstOnceForShowAddFriendAlert=_hasFirstOnceForShowAddFriendAlert;
@property(nonatomic) _Bool hasSyncData; // @synthesize hasSyncData=_hasSyncData;
@property(nonatomic) _Bool hasFirstOnce; // @synthesize hasFirstOnce=_hasFirstOnce;
@property(nonatomic) _Bool hasPasswordSet; // @synthesize hasPasswordSet=_hasPasswordSet;
@property(nonatomic) _Bool hasLmIdSet; // @synthesize hasLmIdSet=_hasLmIdSet;
@property(copy, nonatomic) NSString *lmId; // @synthesize lmId=_lmId;
@property(copy, nonatomic) NSString *id_p; // @synthesize id_p=_id_p;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

