//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface SMUTility : NSObject
{
}

+ (long long)topViewControllerType;
+ (UIViewController *)_topViewController:(id)arg1;
+ (UIViewController *)topViewController;
+ (void)hideHUDNoAnimation;
+ (void)hideHUD;
+ (void)showHUDOnView:(id)arg1;
+ (void)showHUD:(id)arg1;
+ (void)showHUDNow;
+ (void)showHUD;
+ (void)showAlertWithError:(id)arg1;
+ (void)showErrorAlert:(id)arg1;
+ (void)showOKAlert:(id)arg1;
+ (void)hiddenProgressHud;
+ (void)hiddenProgressAlert;
+ (void)showProgressAlert:(id)arg1;
+ (void)showDebugAlert:(id)arg1;
+ (void)showAlert:(id)arg1;
+ (void)showAlert:(id)arg1 animated:(_Bool)arg2;

@end

