//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "UIViewController.h"
//
//#import "SMViewControllerPopupMenuDataSource.h"

@class NSString, SMEmptyView, SMNavigationBar, SMTextFieldAlertView, UIButton;

@interface SMViewController : UIViewController //<SMViewControllerPopupMenuDataSource>
{
    UIButton *leftButton;
    UIButton *rightButton;
    _Bool _showBackButton;
    _Bool _showAudioTextButton;
    _Bool _currentTextState;
    _Bool _showLeftItem;
    _Bool _showRightItem;
    SMNavigationBar *_navBarView;
    SMEmptyView *_emptyDataView;
    id/*CDUnknownBlockType*/ _callBack;
    SMTextFieldAlertView *_starAlert;
}

@property(retain, nonatomic) SMTextFieldAlertView *starAlert; // @synthesize starAlert=_starAlert;
@property(copy, nonatomic) id/*CDUnknownBlockType*/ callBack; // @synthesize callBack=_callBack;
@property(nonatomic) _Bool showRightItem; // @synthesize showRightItem=_showRightItem;
@property(nonatomic) _Bool showLeftItem; // @synthesize showLeftItem=_showLeftItem;
@property(nonatomic) _Bool currentTextState; // @synthesize currentTextState=_currentTextState;
@property(nonatomic) _Bool showAudioTextButton; // @synthesize showAudioTextButton=_showAudioTextButton;
@property(nonatomic) _Bool showBackButton; // @synthesize showBackButton=_showBackButton;
@property(retain, nonatomic) SMEmptyView *emptyDataView; // @synthesize emptyDataView=_emptyDataView;
@property(retain, nonatomic) SMNavigationBar *navBarView; // @synthesize navBarView=_navBarView;
- (long long)preferredStatusBarStyle;
- (void)didClickAlertCancelButton;
- (void)showStarAlert;
- (id)_topViewController:(id)arg1;
- (id)topViewController;
- (void)setUpRightNarItem;
- (void)setUpLeftNarItem;
- (void)hideEmptyDataView;
- (void)showEmptyDataView;
- (void)setImageForRightItemWith:(id)arg1;
- (void)setImageForLeftItem;
- (void)refreshLeftButtonState:(_Bool)arg1;
- (void)refreshRightButtonState:(_Bool)arg1;
- (void)setTitle:(id)arg1;
- (double)getButtonWidth:(id)arg1;
- (id)getButtonWithItem:(long long)arg1 title:(id)arg2 addTarget:(id)arg3 action:(SEL)arg4;
- (void)setBarLeftButtonTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3 type:(unsigned long long)arg4;
- (void)setBarRightButtonTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3 type:(unsigned long long)arg4;
- (void)setBarLeftButtonItem:(long long)arg1 addTarget:(id)arg2 action:(SEL)arg3;
- (void)setBarRightButtonItem:(long long)arg1 addTarget:(id)arg2 action:(SEL)arg3;
- (void)pop:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)showJoinGroupAlertWithTeamId:(id)arg1;
- (id/*CDUnknownBlockType*/)menuActionBlock;
- (id)menuImages;
- (id)menuItems;
- (void)sendQuickMessage;
- (void)exchangeCard;
- (void)goToContacts;
- (void)createNormalTeam;
- (void)createTeam;
- (void)scanQRcode;
- (void)origin_goToAliPay;
- (void)goToAliPay;
- (void)removeNotification;
- (void)addNotification;
- (void)startTimer;
- (void)closeHUD;
- (void)close;
- (void)addFriend;
- (void)showPopView:(id)arg1;
- (_Bool)shouldShowRedPoint;
- (void)_refreshRedPoint;
- (void)refreshRedPoint;
- (void)setUpRightNarItem;
- (void)profileCallback;
- (void)setUpLeftNarItem;
- (void)goToAccount;
- (id/*CDUnknownBlockType*/)menuActionBlock;
- (id)menuItems;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

